spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:test/config-repo.git
          username: test
          password: test
          search-paths: application
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082



