spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:qqq19923/config-repo.git
          username: test
          password: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082



